### ISSUE TITLE
Enable requirement loading as part of util scripts at start of notebook.

### ISSUE THREAD

**Issue by jannesgg** [ocean-data-factory-sweden/kso-utils#49]
The idea here is to load the requirements in a single line instead of the big block we have at the beginning of every tutorial. E.g. load_env function that is used from somewhere else.

**Comment by victor-wildlife** [comment]
FWIW at the moment the install kso_data_management and requirements take +10 mins to run

**Comment by jannesgg** [comment]
Happy to report that I have moved some things around and cleaned up a bit. This is the new time: 

All packages are installed and ready to go!
CPU times: user 1.52 s, sys: 261 ms, total: 1.78 s
Wall time: 2min 15s

**Comment by Diewertje11** [comment]
This isssue is closed by commit 1 commit d64544c from merge request: Package dependency fix 195.
