### ISSUE TITLE
Set tut #6 to test ML in Spyfish

### ISSUE THREAD

**Issue by jannesgg** [ocean-data-factory-sweden/kso-utils#6]
Set up tut#6 to run the fish identification model developed in https://wandb.ai/adi-ohad-heb-uni/project-wildlife-ai?workspace=user-victor-wildlife for the Spyfish Aotearoa project

**Comment by jannesgg** [comment]
@victor-wildlife I have been working on this and it seems the big hurdle right now is the format of the model that was trained. It is a PyTorch model but it isn't a YOLO model, which means that it isn't directly transferable to our current framework. Since this is likely something we want to support (custom models), I will spend some more time looking into it but it will require a bit more work than I initially thought. My aim will be to incorporate their model code in some way but keep a lot of the YOLO utils that help us work with video streams etc. We can also discuss this more next week.

**Comment by victor-wildlife** [comment]
Sounds good. Let's see how long it takes to develop the capabilities to support the custom model. Alternatively, we could look at some of the [formats support from CVAT](https://github.com/opencv/cvat/tree/f62aa276cdd103289a0a5e44343c27e695c9b733/cvat/apps/dataset_manager/formats)

**Comment by jannesgg** [comment]
@victor-wildlife Have done some more digging into this and think we can discuss the outcome during our technical session this week :)

**Comment by victor-wildlife** [comment]
Awesome, looking forward to the catch-up session this week.

Cheers,
Victor

**Comment by jannesgg** [comment]
Closing this for now as we try to train new YOLO models first and then return to testing the integration of custom models as it becomes necessary.
