### ISSUE TITLE
Error loading clips to Zoo from Colab

### ISSUE THREAD

**Issue by victor-wildlife** [ocean-data-factory-sweden/kso-utils#77]
While trying to upload clips to Zooniverse with tutorial #3 I get the following error: 'PosixPath' object has no attribute 'close',

It looks like the subject.add_location function from panoptes is not recognising the path of the file? Any thoughts/suggestions on how to debug would be more than welcome

![Image](https://github.com/ocean-data-factory-sweden/kso-utils/assets/55268669/183c7cff-72ee-44b5-8552-9410021b15bb)

**Comment by Diewertje11** [comment]
Hej!
on top of which commit are you and trying to run it? 
I tried it from my own branch that is on top of commit 29af48b, and there I got this:
<img width="743" alt="GetImage (1)" src="https://github.com/ocean-data-factory-sweden/kso-utils/assets/47739872/ab4b5c0a-8279-4fba-a7d0-e5b5410a33b0">

And when I tried to run it on top of the curent dev, so commit  5ec631e, then I got this:
<img width="739" alt="Screenshot 2023-05-12 084853" src="https://github.com/ocean-data-factory-sweden/kso-utils/assets/47739872/e397d737-f334-46b6-a569-5e3e9c278b2f">

So I am not getting the same error, but two different ones. (I have not looked at what the difference is between the commits yet, but need to work on something else now.)

I can take a look at it later again, but maybe knowing that I do not get the same error, but different ones, already helps?

I ran it locally with the template project.

**Comment by victor-wildlife** [comment]
@Diewertje11 Thanks for the info. I was working on the current dev branch (5ec631e). I am not sure about the first error but the second error you get is because the dataset name that is trying to create in Zooniverse has already been created. You can try renaming the dataset it creates or renaming the existing one. Let me know if you get to upload the files to zoo using the template project.
Thanks!

**Comment by victor-wildlife** [comment]
Closing this issue as it was marked as done
