### ISSUE TITLE
yolo_utils has 2x a function called track_objects

### ISSUE THREAD

**Issue by Diewertje11** [ocean-data-factory-sweden/kso-utils#87]
@jannesgg and @victor-wildlife 

the 2 track_object functions in yolo_utils do something differently. I have not looked into when they were both added, but I don't know which one should be used there and whether 1 of them is just old? Can one of you take a look at this?

**Comment by Diewertje11** [comment]
There is also some duplication in widgets.py:
select_eventdate and select_modification
Here the functions do approximately the same, just differ slightly.

**Comment by victor-wildlife** [comment]
Good catch, I will clean "select_eventdate", "select_modification" and "update_new_deployments"

**Comment by Diewertje11** [comment]
select_eventdate, update_new_deployments are resolved in PR #105 Code cleanup + ...

track_objects and select_modification are still double

**Comment by jannesgg** [comment]
Fixed in #[8d43b2c](https://github.com/ocean-data-factory-sweden/kso/commit/8d43b2c3ce82dfacce93063ea3dfc3663bf843cf)
